### ISSUE TITLE
bug: down active_trigger_chains breaks listening for all trigger listeners

### ISSUE THREAD

**Issue by reecepbcups** [Lay3rLabs/WAVS#606]
## Summary

I had the following in my WAVS config. I registered the services and all that, but wavbs would not watch for the events. I figured it was RPC so i changed this multiple times to other working provides, did nothing.

```toml
[default.chains.evm.holesky]
chain_id = "17000"
ws_endpoint = "wss://ethereum-holesky-rpc.publicnode.com"
http_endpoint = "https://ethereum-holesky-rpc.publicnode.com"
poll_interval_ms = 7000

[wavs]
active_trigger_chains = ["local", "holesky"]
```

Finally moved to just

```
active_trigger_chains = ["holesky"]
```

and it worked, events were being processed and output to stdout when I triggered a component with no other changes

## bug

If `active_trigger_chains` contains any networks that are down, it breaks listening for all.

## Questions
- Can we just watch all chains? (maybe by default we put ["*"] ? (or health checks on start / panic)
- if not, just support for multiple again would be great
