### ISSUE TITLE
aggregator only sends to `local` even when service states `holesky` in service URI?

### ISSUE THREAD

**Issue by reecepbcups** [Lay3rLabs/WAVS#639]
ref https://docs.google.com/document/d/1RKWQHckHPGzGu6cRc9pQQEyXEWX8WnkXoHQ5yhBLmYU/edit?tab=t.0

## Summary

** Aggregator (beta.2): for some reason it only sends to localhost, so I have to override the wavs.toml aggregator section to have the local chain be the holesky endpoints

The entire setup can be found in the private https://github.com/Lay3rLabs/testnet repo.

## Service URI

https://coffee-deliberate-wasp-48.mypinata.cloud/ipfs/bafkreiemquadvcpcjdccgjafcsoleghj6gpvp5mcjr56d7d3gnrgfc5w4y

## Aggregator wavs.toml

live instance: http://54.242.82.25:8001/config

```toml
[default]
log_level = ["info", "wavs=debug"]

[default.chains.evm.local]
chain_id = "31337"
# when I had this i would get an error in the aggregator for localhost:8545 requests. restarted it with this new config and it worked
# ws_endpoint = "ws://localhost:8545"
# http_endpoint = "http://localhost:8545"
ws_endpoint = "wss://ethereum-holesky-rpc.publicnode.com"
http_endpoint = "https://ethereum-holesky-rpc.publicnode.com"
poll_interval_ms = 7000

[default.chains.evm.holesky]
chain_id = "17000"
ws_endpoint = "wss://ethereum-holesky-rpc.publicnode.com"
http_endpoint = "https://ethereum-holesky-rpc.publicnode.com"

[aggregator]
# The directory to store the data. Default is "/var/wavs-aggregator"
data = "/wavs/aggregator-data"

cors_allowed_origins = [
    "https://lay3rlabs.github.io/*",
    "http://localhost:*",
    "http://127.0.0.1:*",
]
```
